### ISSUE TITLE
Error occurs if second SBOM has no files

### ISSUE THREAD

**Issue by Malcolmnixon** [anthonyharrison/sbommerge#1]
If the second SBOM has no files listed (`"files": [],`) then the program fails.

This was tracked down to an issue in libsbom (https://github.com/anthonyharrison/lib4sbom/issues/29) where `SBOMParser.get_files()` erroneously returns a dictionary when the SBOM contains an empty files list.

The result is the following error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\sbommerge.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\sbommerge\cli.py", line 148, in main
    if file in files2:
       ^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by anthonyharrison** [comment]
Fixed via https://github.com/anthonyharrison/lib4sbom/issues/29
